USE [SIMSERVER];

CREATE TABLE UserInfo(
	UserID VARCHAR(20) NOT NULL PRIMARY KEY,
	UserPW VARCHAR(100) NOT NULL,
	SignData DATE DEFAULT GETDATE()
);

CREATE TABLE CharacterInfo(
	UserID VARCHAR(20) NOT NULL PRIMARY KEY,
    X INT DEFAULT 0,
    Y INT DEFAULT 0,
	Lv INT DEFAULT 1,
    Exp INT DEFAULT 0,
    HP INT DEFAULT 100,
    FOREIGN KEY (UserID) REFERENCES UserInfo(UserID)
);